# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    # Specify labels for npm pull requests
    labels:
      - "dependencies"
      - "npm"
    # Limit the number of open pull requests
    open-pull-requests-limit: 10
    # Group related updates to reduce PR noise
    groups:
      react-packages:
        patterns:
          - "react"
          - "react-*"
          - "@types/react*"
        exclude-patterns:
          - "react-leaflet"
      typescript-packages:
        patterns:
          - "typescript"
          - "@typescript-eslint/*"
          - "@types/*"
    # Define auto-approval criteria
    ignore:
      # Don't update to React versions that need breaking changes
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
