# Cloudflare Pages configuration for Champagne Festival
name = "champagnefestival"
compatibility_date = "2024-03-14"

# Build configuration
# This points to Vite's output directory
pages_build_output_dir = "dist"

# Redirects all paths to index.html for SPA routing
[[routes]]
pattern = "/*"
script = ""
destination = "/index.html"